-- =============================================================================
-- LAB CHAIN SCHEMA  (rev 3)
-- Chain: Formulation → Production Run → Measurement → Outcome
-- Source: grounded from INTUMESCENT_NEW_FORMULATIONS_2026-04-05.xlsx (BASE-003)
-- Scope: strictly this chain only
--
-- LOCKED DECISIONS (David, 2026-04-07):
--   D1  measurements.production_run_id is NOT NULL.
--       Historical rows link to a synthetic HIST-run. Confidence tracked in
--       measurements.linkage_confidence.
--   D2  production_date is NEVER inferred from source_id. NULL for all historical.
--       days_since_production is NULL when production_date is NULL.
--   D3  Formulation identity is per-file: UNIQUE(source_file, source_id).
--   D4  outcomes table scope = INTUMESCENT viscosity tests only.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- =============================================================================
-- TABLE 1: formulations
-- Per-file identity (D3). Cross-file comparison via base_id at query time.
-- =============================================================================
CREATE TABLE IF NOT EXISTS formulations (
  id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- D4: normalized core ID — DD.MM.YYYY-NNN pattern, year always 4 digits.
  -- Suffixes like "(הכנה 3.7.23)" or "(1)" are stripped into id_suffix.
  source_id         TEXT          NOT NULL,

  -- D4: text after the core ID in the original cell, stripped of parens/spaces.
  -- e.g. "הכנה 3.7.23" from "29.06.2023-017 (הכנה 3.7.23)". NULL when absent.
  id_suffix         TEXT          NULL,

  -- D4: exact cell value before normalization — never discarded.
  raw_source_id     TEXT          NOT NULL,

  base_id           TEXT          NOT NULL,
  version           TEXT          NULL,
  product_name      TEXT          NULL,
  source_file       TEXT          NOT NULL,
  source_sheet      TEXT          NOT NULL,
  raw_formula_notes TEXT          NULL,

  -- D2: expected sum of all material fractions for this formulation.
  -- INTUMESCENT file uses scale=2.0. Standard chemistry uses scale=1.0.
  -- Do NOT normalize fractions — store this instead.
  composition_scale NUMERIC(4,2)  NOT NULL DEFAULT 2.0,

  created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),

  CONSTRAINT formulations_source_file_id_uq UNIQUE (source_file, source_id)
);

CREATE INDEX IF NOT EXISTS idx_formulations_base_id    ON formulations (base_id);
CREATE INDEX IF NOT EXISTS idx_formulations_source_id  ON formulations (source_id);
CREATE INDEX IF NOT EXISTS idx_formulations_base_cross ON formulations (base_id, source_file);


-- =============================================================================
-- TABLE 1b: formulation_materials
-- =============================================================================
CREATE TABLE IF NOT EXISTS formulation_materials (
  id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  formulation_id   UUID          NOT NULL REFERENCES formulations(id) ON DELETE CASCADE,
  material_name    TEXT          NOT NULL,
  fraction         NUMERIC(10,7) NOT NULL,
  functional_group TEXT          NULL,
  col_index        INTEGER       NOT NULL,

  CONSTRAINT formulation_materials_uq UNIQUE (formulation_id, material_name)
);

CREATE INDEX IF NOT EXISTS idx_fm_formulation_id ON formulation_materials (formulation_id);
CREATE INDEX IF NOT EXISTS idx_fm_material_name  ON formulation_materials (material_name);


-- =============================================================================
-- TABLE 2: production_runs
--
-- D1: Synthetic HIST-runs have batch_id_is_synthetic = TRUE and run_origin =
--     'HISTORICAL'. These are not real physical batches.
-- D2: production_date is ALWAYS NULL for HISTORICAL runs. Must not be inferred.
-- =============================================================================
CREATE TABLE IF NOT EXISTS production_runs (
  id                       UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id                 TEXT          NOT NULL UNIQUE,

  -- D4: TRUE when batch_id was generated by the ingest script, not from a
  --     real lab record. Must never be treated as ground truth.
  batch_id_is_synthetic    BOOLEAN       NOT NULL DEFAULT FALSE,

  formulation_id           UUID          NOT NULL REFERENCES formulations(id),

  -- D2: NULL for all HISTORICAL runs. Only set from a real production record.
  production_date          DATE          NULL,

  operator                 TEXT          NULL,
  production_temperature_c NUMERIC(5,1)  NULL,
  foaming_event            BOOLEAN       NULL,

  -- Free-text from tests sheet col 0 (rows 5/10/15). Verbatim.
  raw_process_notes        TEXT          NULL,

  -- 'HISTORICAL' = synthetic run created at ingest from Excel only.
  -- 'REAL'       = run created from an actual production record.
  run_origin               TEXT          NOT NULL DEFAULT 'HISTORICAL'
                             CHECK (run_origin IN ('HISTORICAL','REAL')),

  created_at               TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pr_formulation_id  ON production_runs (formulation_id);
CREATE INDEX IF NOT EXISTS idx_pr_run_origin      ON production_runs (run_origin);
CREATE INDEX IF NOT EXISTS idx_pr_synthetic       ON production_runs (batch_id_is_synthetic);


-- =============================================================================
-- TABLE 2b: production_steps
-- =============================================================================
CREATE TABLE IF NOT EXISTS production_steps (
  id                   UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  production_run_id    UUID    NOT NULL REFERENCES production_runs(id) ON DELETE CASCADE,
  step_sequence        INTEGER NOT NULL,
  material_name        TEXT    NOT NULL,
  mixing_duration_min  INTEGER NULL,
  mixing_speed_rpm     INTEGER NULL,
  raw_step_instruction TEXT    NULL,

  CONSTRAINT production_steps_sequence_uq UNIQUE (production_run_id, step_sequence)
);

CREATE INDEX IF NOT EXISTS idx_ps_production_run_id ON production_steps (production_run_id);


-- =============================================================================
-- TABLE 3: measurements
--
-- Fix 1: UNIQUE(production_run_id, test_date) prevents duplicate measurements
--        on re-ingest of the same file. ON CONFLICT DO NOTHING is the guard.
--
-- D1: production_run_id NOT NULL — always linked to a HIST-run for historical data.
-- D2: days_since_production NULL when production_date is NULL (all historical).
-- =============================================================================
CREATE TABLE IF NOT EXISTS measurements (
  id                        UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  production_run_id         UUID          NOT NULL REFERENCES production_runs(id),
  test_date                 DATE          NOT NULL,

  -- D2: NULL for all historical. Computed only when production_date is known.
  days_since_production     INTEGER       NULL,

  measurement_temperature_c NUMERIC(5,1)  NULL,
  spindle_type              TEXT          NULL,

  -- D1: Confidence of the production_run_id assignment.
  --   'EXACT'               — matched by an explicit batch record
  --   'HEURISTIC_SOURCE_ID' — matched by formulation source_id only (historical)
  --   'MANUAL'              — assigned manually after ingest
  linkage_confidence        TEXT          NOT NULL DEFAULT 'HEURISTIC_SOURCE_ID'
                              CHECK (linkage_confidence IN ('EXACT','HEURISTIC_SOURCE_ID','MANUAL')),
  linkage_note              TEXT          NULL,

  created_at                TIMESTAMPTZ   NOT NULL DEFAULT now(),

  -- Fix 1: idempotency constraint — one measurement per run per test date
  CONSTRAINT measurements_run_date_uq UNIQUE (production_run_id, test_date)
);

CREATE INDEX IF NOT EXISTS idx_meas_production_run_id ON measurements (production_run_id);
CREATE INDEX IF NOT EXISTS idx_meas_test_date         ON measurements (test_date);
CREATE INDEX IF NOT EXISTS idx_meas_linkage           ON measurements (linkage_confidence);


-- =============================================================================
-- TABLE 4: outcomes
-- D4: INTUMESCENT viscosity tests only. Fixed columns are intentional.
--     Future test types require a new table, not an extension of this one.
-- =============================================================================
CREATE TABLE IF NOT EXISTS outcomes (
  id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  measurement_id       UUID         NOT NULL REFERENCES measurements(id) ON DELETE CASCADE,
  ph                   NUMERIC(4,2) NULL,
  specific_gravity     NUMERIC(6,4) NULL,
  viscosity_6rpm_cps   INTEGER      NULL,
  viscosity_12rpm_cps  INTEGER      NULL,
  viscosity_30rpm_cps  INTEGER      NULL,
  viscosity_60rpm_cps  INTEGER      NULL,

  CONSTRAINT outcomes_measurement_uq UNIQUE (measurement_id)
);

CREATE INDEX IF NOT EXISTS idx_outcomes_measurement_id ON outcomes (measurement_id);


-- =============================================================================
-- TABLE 5: ingest_quarantine
-- Fix 2: Stores test records that could not be matched to any formulation in the
--        summary sheet. Not silently dropped. Must be reviewed manually.
-- =============================================================================
CREATE TABLE IF NOT EXISTS ingest_quarantine (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  source_file   TEXT        NOT NULL,
  source_sheet  TEXT        NOT NULL,
  raw_source_id TEXT        NOT NULL,   -- exact value from the Excel cell
  test_date     TEXT        NULL,       -- raw string — may be unparseable
  raw_row_json  JSONB       NOT NULL,   -- full row data, verbatim
  reason        TEXT        NOT NULL,   -- why it was quarantined
  ingested_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ingest_quarantine_source_id_date_uq UNIQUE (source_file, raw_source_id, test_date)
);

CREATE INDEX IF NOT EXISTS idx_quarantine_source_file ON ingest_quarantine (source_file);
CREATE INDEX IF NOT EXISTS idx_quarantine_raw_id      ON ingest_quarantine (raw_source_id);


-- =============================================================================
-- VALIDATION VIEWS
-- =============================================================================

-- V1: Composition sum per formulation — validates against composition_scale (D2)
CREATE OR REPLACE VIEW v_formulation_composition_check AS
SELECT
  f.source_id,
  f.source_file,
  f.base_id,
  f.version,
  f.composition_scale,
  ROUND(SUM(fm.fraction)::NUMERIC, 6)                   AS total_fraction,
  ABS(SUM(fm.fraction) - f.composition_scale) < 0.005   AS sum_valid
FROM formulations f
JOIN formulation_materials fm ON fm.formulation_id = f.id
GROUP BY f.id, f.source_id, f.source_file, f.base_id, f.version, f.composition_scale;


-- V2: Composition differences between versions of the same base_id (same file)
CREATE OR REPLACE VIEW v_version_composition_diff AS
SELECT
  a.source_file,
  a.base_id,
  a.source_id          AS version_a,
  b.source_id          AS version_b,
  a_mat.material_name,
  a_mat.fraction       AS fraction_a,
  b_mat.fraction       AS fraction_b,
  ABS(a_mat.fraction - b_mat.fraction) AS delta
FROM formulations a
JOIN formulations b
  ON a.base_id = b.base_id
 AND a.source_file = b.source_file
 AND a.id < b.id
JOIN formulation_materials a_mat ON a_mat.formulation_id = a.id
JOIN formulation_materials b_mat
  ON b_mat.formulation_id = b.id
 AND b_mat.material_name = a_mat.material_name
WHERE ABS(a_mat.fraction - b_mat.fraction) > 0.0005;


-- V3: Production runs with no step data
CREATE OR REPLACE VIEW v_runs_missing_process_data AS
SELECT
  pr.batch_id,
  pr.run_origin,
  pr.batch_id_is_synthetic,
  f.source_id AS formulation,
  pr.production_date,
  COUNT(ps.id)              AS steps_recorded,
  COUNT(ps.mixing_speed_rpm) AS steps_with_speed,
  CASE
    WHEN COUNT(ps.mixing_speed_rpm) = 0 THEN 'NO PROCESS DATA'
    WHEN COUNT(ps.mixing_speed_rpm) < COUNT(ps.id) THEN 'PARTIAL PROCESS DATA'
    ELSE 'COMPLETE'
  END AS process_data_status
FROM production_runs pr
JOIN formulations f ON f.id = pr.formulation_id
LEFT JOIN production_steps ps ON ps.production_run_id = pr.id
GROUP BY pr.id, pr.batch_id, pr.run_origin, pr.batch_id_is_synthetic, f.source_id, pr.production_date;


-- V4: days_since_production correctness (only where production_date is set)
CREATE OR REPLACE VIEW v_measurement_age_check AS
SELECT
  pr.batch_id,
  f.source_id AS formulation,
  pr.production_date,
  m.test_date,
  m.days_since_production             AS stored_days,
  (m.test_date - pr.production_date)  AS computed_days,
  m.days_since_production = (m.test_date - pr.production_date) AS days_correct
FROM measurements m
JOIN production_runs pr ON pr.id = m.production_run_id
JOIN formulations f ON f.id = pr.formulation_id
WHERE pr.production_date IS NOT NULL;


-- V5: Linkage confidence distribution
CREATE OR REPLACE VIEW v_linkage_confidence_summary AS
SELECT
  pr.run_origin,
  m.linkage_confidence,
  COUNT(*) AS measurement_count
FROM measurements m
JOIN production_runs pr ON pr.id = m.production_run_id
GROUP BY pr.run_origin, m.linkage_confidence
ORDER BY pr.run_origin, m.linkage_confidence;


-- V6: Quarantine summary
CREATE OR REPLACE VIEW v_quarantine_summary AS
SELECT
  source_file,
  reason,
  COUNT(*) AS record_count,
  MIN(ingested_at) AS first_seen,
  MAX(ingested_at) AS last_seen
FROM ingest_quarantine
GROUP BY source_file, reason
ORDER BY source_file, record_count DESC;
